### ISSUE TITLE
Need help when activating X12DPG-QT6.

### ISSUE THREAD

**Issue by nahso** [zsrv/supermicro-product-key#6]
Hi,
I am trying to activate X12DPG-QT6 using JSON file.

I used
```
./supermicro-product-key nonjson encode --sku SFT-DCMS-SINGLE <my-mac>
```
to generate a private key, then insert the key to the json template, then I got:
```
'{"ProductKey":{"Node":{"LicenseID":"1","LicenseName":"SFT-OOB-LIC","CreateDate":"20240422"},"Signature":"<key>"}}'
```

But when I tried to verify this key by:
```
./supermicro-product-key json verify <my-mac> '{"ProductKey":{"Node":{"LicenseID":"1","LicenseName":"SFT-OOB-LIC","CreateDate":"20240422"},"Signature":"<key>"}}'
```
I got a error:
```
Error: product key verification failed: crypto/rsa: verification error
```

and this key can not be activated in the HTML5 interface either.

Is there any error in my operation? Thank you.

**Comment by zsrv** [comment]
It is not possible to generate JSON keys (without the RSA private key that Supermicro uses to sign them). This utility can only verify existing JSON keys.
