### ISSUE TITLE
Unable to activate key for X9DRD-7LN4F-JBOD

### ISSUE THREAD

**Issue by 0verEngineer** [zsrv/supermicro-product-key#7]
Hey, i generated a key:

`./supermicro-product-key nonjson encode --sku SFT-DCMS-SINGLE 0cc47a1caa7b`

And i tried to activate it:

`.\sum.exe -i 192.168.178.105 -u ADMIN -p ADMIN -c ActivateProductKey --key AAYAAAAAAAAAAAAAAAAAAKwTbDdZnqLclWcy6WdrV4X9KkRnc3QTU+HWF47tI9wS7vhb8Xzn+XLzUqLChqmEJmHY9GVovLHGbqgbQGkdGPTmIIp3ZtGOTNbEsYKCF2yCVbnVwwgWhu0pYTAmMHpSfiU3XpaARH+kvRryNcTuKkPlxRHW3N1yaECTO3snNEiNSmI+6O46wdr5RoR5ICce/hjcoe77HTTcIQCBgjp3B26LeSBRIkXmBSe7wlEXCIquJzYqAfyLytnzDb4qGVD6CBu5MStbzqRgfnfgpt8CxWesVYvhm+/BGf8pKFGtCWUL1MCPjJXr//4WwbgXrMwXig==`

But i got this response:

`Supermicro Update Manager (for UEFI BIOS) 2.14.0 (2024/02/15) (x86_64)
Copyright(C) 2013-2024 Super Micro Computer, Inc. All rights reserved.

********************************<<<<<ERROR>>>>>*********************************

ExitCode                = 149
Description             = IPMI execution failed
Program Error Code      = 278.21
Error message:
        Can't execute Read SW FRU Data CC (Invalid data field in Request)

********************************************************************************`

Do you have any idea?

**Comment by zsrv** [comment]
As far as I'm aware, the only key type that may be accepted by an X9 board is SFT-OOB-LIC: https://github.com/zsrv/supermicro-product-key?tab=readme-ov-file#platform-support

**Comment by 0verEngineer** [comment]
Thanks a lot, but i don't get how i can generate the SFT-OOB-LIC key, is it possible?

**Comment by zsrv** [comment]
The "original" SFT-OOB-LIC can be generated using a different command: https://github.com/zsrv/supermicro-product-key?tab=readme-ov-file#oob-keys

**Comment by 0verEngineer** [comment]
Oh thanks, i did not see it in the readme sorry.
