### ISSUE TITLE
This platform does not support SW FRU node product key (SYS-510T-MR-EU)

### ISSUE THREAD

**Issue by hendymen** [zsrv/supermicro-product-key#8]
I'm having difficulty in creating key for SYS-510T-MR-EU.

********************************<<<<<ERROR>>>>>*********************************

ExitCode                = 61
Description             = Utility internal error
Program Error Code      = 260.10
Error message:
    This platform does not support SW FRU node product key.

********************************************************************************

**Comment by hendymen** [comment]
supermicro-product-key.exe nonjson encode --sku SFT-DCMS-SINGLE 3cecef123456

**Comment by zsrv** [comment]
This system has motherboard X12STH-SYS, which would only support JSON keys.
